### PR TITLE
DOSPERT update - including changes mentioned in previous test

### PR DESCRIPTION
**Pull request by katharineholmes46**

### CODE REVIEW

**Comment by angelaradulescu** [comment]
oh wow. a pull request I can merge on the first try! :-) 

can you briefly note the changes? not sure what the "previous test" is... 

ps: what do you think, can we be ready to go by 3/17? I have to do journal club that day, and I was thinking we can also do a joint mini on this project.

**Comment by katharineholmes46** [comment]
yeah, i think we could.  (previous test simply meant that when we figured
out the problems with GIT, we recommitted DOSPERT but without really making
any changes, so this commit included the changes in the note of the
previous commit: fullscreen, separate pages, fixed images).

and yeah, i think we could be good to go by then.  right now i'm still
working on the function of how to stop DOSPERT from continuing without
answering all the questions but thats it.  is there anything else you want
me to fix/work on?

**Comment by angelaradulescu** [comment]
I see! ok, great. this leaves the holt and laury instructions and just general code clean-up? I'll take care of those two and hopefully merging experiments once individual tasks are done. 

if you sort out the continue issue, maybe start looking into data downloading? I know psiturk has an actual function for this (http://psiturk.readthedocs.org/en/latest/command_line/download_datafiles.html). ideally, we can do a quick a pilot locally (e.g. one of us does the experiment for real), then retrieve the .csv file and analyze the output in MATLAB to make sure the data make sense.

**Comment by katharineholmes46** [comment]
awesome sauce - will do :)

**Pull request merged**
